let featureSource = [
  {
    name: "Lune",
    address:
      "enter via, Shop 16/161 Collins Street, Russell St, Melbourne VIC 3000",
    time: "weekdays: 07:30-15:00\nweekends:\n08:30-15:00",
    phone: "",
    website: "https://www.lunecroissanterie.com/",
    brief: "Great Croissanterie",
    tag: "brunch",
    lat: -37.81553796,
    long: 144.9692209,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Manchester Press",
    address: "8 Rankins Ln, Melbourne VIC 3000",
    time: "08:30-16:00",
    phone: 61426987017,
    website: "https://www.facebook.com/manchesterpress",
    brief:
      "Choice coffee, brekkie & bagels in a bright, airy space with eclectic decor & a vintage-chic vibe.",
    tag: "brunch",
    lat: -37.81387222,
    long: 144.9621355,
    lineA: 1,
    lineB: 1,
    lineC: "",
  },
  {
    name: "Vacation",
    address: "1 Exhibition St, Melbourne VIC 3000",
    time: "07:00-14:00\n07:00-13:30",
    phone: 61396622013,
    website: "http://vacationcoffee.com.au/",
    brief:
      "Everything on the menu has gluten-free options, and a decent amount of their dishes are vegan.",
    tag: "brunch",
    lat: -37.81581337,
    long: 144.9721394,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "White mojo",
    address: "115 Hardware St, Melbourne VIC 3000",
    time: "07:00-16:00\n08:00-16:00",
    phone: 61390788119,
    website: "https://www.whitemojo.com.au/",
    brief:
      "Over the top brunch options abound at White Mojo, choose from classics their signature croissant burger, soft shell crab, chipotle mayo with fried eggs and a chorizo crumb is a definite must.",
    tag: "brunch",
    lat: -37.81213675,
    long: 144.9604816,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Operator 25",
    address: "25 Wills St, Melbourne VIC 3000",
    time: "07:00-16:00\n08:00-16:00",
    phone: 61396703278,
    website: "http://www.operator25.com.au/",
    brief:
      "Brunch cafe and coffee hangout in an early 1900s building that housed Melbourne's first switchboard.",
    tag: "brunch",
    lat: -37.81068997,
    long: 144.957004,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Melbourne Central",
    address: "Swanston St, Melbourne VIC 3000, Australia",
    time: "10AM-9PM",
    phone: 61399221122,
    website: "http://www.melbournecentral.com.au/",
    brief:
      "Various retailers & dining options, plus a cinema, offered in a multilevel space with a glass dome.",
    tag: "scenic point",
    lat: -37.81025373,
    long: 144.9627805,
    lineA: 2,
    lineB: 2,
    lineC: "",
  },
  {
    name: "Parliament house",
    address: "Spring St, East Melbourne VIC 3002",
    time: "08:30-17:30",
    phone: 61396518911,
    website: "http://www.parliament.vic.gov.au/",
    brief:
      "Seat of Victoria's parliament built in 1856 with 2 legislative chambers and grand colonnaded facade.",
    tag: "scenic point",
    lat: -37.81099811,
    long: 144.9738288,
    lineA: 5,
    lineB: 5,
    lineC: 4,
  },
  {
    name: "State library",
    address: "328 Swanston St, Melbourne VIC 3000, Australia",
    time: "10:00-18:00",
    phone: 61386647000,
    website: "https://www.slv.vic.gov.au/",
    brief:
      "Victorian landmark, opened in 1856, consisting of 23 classical buildings, with a grand reading room.",
    tag: "scenic point",
    lat: -37.80978858,
    long: 144.9651951,
    lineA: 3,
    lineB: 3,
    lineC: "",
  },
  {
    name: "ACDC Lane",
    address: "ACDC La, Melbourne VIC 3000, Australia",
    time: "24H",
    phone: "Nan",
    website: "Nan",
    brief:
      "Australian rock legends ACDC are celebrated by this large graffiti mural depicting them in action.",
    tag: "scenic point",
    lat: -37.8155505,
    long: 144.9709085,
    lineA: 4,
    lineB: 4,
    lineC: "",
  },
  {
    name: "Hosier lane",
    address: "Hosier lane, Melbourne, VIC 3000, Australia",
    time: "24H",
    phone: "Nan",
    website: "Nan",
    brief: "Graffiti",
    tag: "scenic point",
    lat: -37.81655126,
    long: 144.9691677,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Desgraves Street",
    address: "Desgraves Street, Melbourne",
    time: "24H",
    phone: "Nan",
    website: "Nan",
    brief: "Graffiti",
    tag: "scenic point",
    lat: -37.81732476,
    long: 144.9657862,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "RMIT",
    address: "435-457 Swanston St, Melbourne VIC 3000, Australia",
    time: "8:30AM-5:30PM",
    phone: 61399252020,
    website: "http://www.rmit.edu.au/library",
    brief:
      "RMIT University, officially the Royal Melbourne Institute of Technology, is a public research university in Melbourne, Australia. Founded in 1887 by Francis Ormond, RMIT began as a night school offering classes in art, science, and technology, in response to the industrial revolution in Australia.",
    tag: "scenic point",
    lat: -37.80818994,
    long: 144.9624139,
    lineA: 6,
    lineB: "",
    lineC: "",
  },
  {
    name: "South Lawn",
    address: "South Lawn, Parkville VIC 3052, Australia",
    time: "24H",
    phone: 61390355511,
    website: "https://maps.unimelb.edu.au/parkville/poi/south_lawn",
    brief:
      "South Lawn is a stunning landmark under the Old Arts clock tower. It is accessible from the Grattan Street gate opposite University square, and flanked by many buildings, including Bailieu library, Old Arts, John Medley and Old Quad.\nEvents and barbecues are frequently held here throughout semester. It is a lovely place to hang out, weather-permitting.",
    tag: "scenic point",
    lat: -37.79864307,
    long: 144.960313,
    lineA: 7,
    lineB: "",
    lineC: "",
  },
  {
    name: "Seven Seeds",
    address: "114 Berkeley St, Carlton VIC 3053",
    time: "08:00-15:00",
    phone: 61393478664,
    website: "http://sevenseeds.com.au/",
    brief:
      "Airy, industrial-chic cafe and micro-roaster serving all-day brunch, salads & specialty teas.",
    tag: "brunch",
    lat: -37.80269398,
    long: 144.9590352,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Unimelb",
    address: "Parkville VIC 3010, Australia",
    time: "24H",
    phone: 61390355511,
    website: "http://www.unimelb.edu.au/",
    brief:
      "Multi-campus public teaching and research institution, founded in 1853, with graduate schools.",
    tag: "scenic point",
    lat: -37.7982264,
    long: 144.9609234,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Queen Victoria Market",
    address: "Queen St, Melbourne VIC 3000, Australia",
    time: "6AM-3PM",
    phone: 61393205822,
    website: "http://www.qvm.com.au/",
    brief:
      "Longtime market selling food, clothing & more in a historic landmark spanning 2 city blocks.",
    tag: "dinner",
    lat: -37.80742573,
    long: 144.9567551,
    lineA: 8,
    lineB: "",
    lineC: "",
  },
  {
    name: "Eureka Skydeck",
    address: "7 Riverside Quay, Southbank VIC 3006, Australia",
    time: "5:30-9PM",
    phone: 61396938888,
    website: "http://www.eurekaskydeck.com.au/",
    brief:
      "Gold-plated observation deck on the 88th floor with panoramic city views & a protruding glass cube.",
    tag: "scenic point",
    lat: -37.82114763,
    long: 144.9647197,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "National Gallery (NGV)",
    address: "180 St Kilda Rd, Melbourne VIC 3006, Australia",
    time: "10am-5pm",
    phone: 61386202222,
    website: "https://www.ngv.vic.gov.au/",
    brief:
      "Public gallery with vast, varied collection of noted Australian and international art and artefacts.",
    tag: "scenic point",
    lat: -37.82261379,
    long: 144.9689146,
    lineA: "",
    lineB: 5,
    lineC: "",
  },
  {
    name: "Shrine of Remembrance",
    address: "Birdwood Ave, Melbourne VIC 3001, Australia",
    time: "10AM-5PM",
    phone: 61396618100,
    website: "http://www.shrine.org.au/",
    brief:
      "Shrine with colonnaded porticos, commemorating World War I with memorials, exhibitions and gardens.",
    tag: "scenic point",
    lat: -37.83054603,
    long: 144.9734451,
    lineA: "",
    lineB: 6,
    lineC: "",
  },
  {
    name: "Crown Casino",
    address: "8 Whiteman St, Southbank VIC 3006, Australia",
    time: "24H",
    phone: 61392928888,
    website:
      "https://www.crownmelbourne.com.au/?utm_source=google&utm_medium=organic&utm_content=crown_melbourne&utm_campaign=gmb",
    brief:
      "Sprawling riverside entertainment complex with 3 hotels, spas, casino, plus restaurants and bars.",
    tag: "scenic point",
    lat: -37.8235629,
    long: 144.9581007,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Stagger lee",
    address: "276 Brunswick St, Fitzroy VIC 3065, Australia",
    time: "7AM-4PM",
    phone: 61394195564,
    website:
      "https://stagger-lees-takeaway.business.site/?utm_source=gmb&utm_medium=referral",
    brief:
      "Breakfast, toasties and single origin coffee in a distressed-brick space with large wooden tables.",
    tag: "brunch",
    lat: -37.79899481,
    long: 144.9785199,
    lineA: "",
    lineB: "",
    lineC: 1,
  },
  {
    name: "Melbourne Museum",
    address: "11 Nicholson St, Carlton VIC 3053, Australia",
    time: "10am-5pm",
    phone: 61383417777,
    website: "https://museumsvictoria.com.au/melbournemuseum",
    brief:
      "Modern building of an institution founded in 1854 containing dinosaur and regional history exhibits.",
    tag: "scenic point",
    lat: -37.80329131,
    long: 144.9717435,
    lineA: "",
    lineB: "",
    lineC: 2,
  },
  {
    name: "Royal Exhibition",
    address: "9 Nicholson St, Carlton VIC 3053, Australia",
    time: "9am-5pm",
    phone: 61392705000,
    website: "https://museumsvictoria.com.au/reb/",
    brief:
      "Landmark 19th-century exhibition centre, topped with a dome, and set amid landscaped gardens.",
    tag: "scenic point",
    lat: -37.80471679,
    long: 144.9716223,
    lineA: "",
    lineB: "",
    lineC: 3,
  },
  {
    name: "Fitzroy Garden",
    address:
      "Fitzroy Gardens, Wellington Parade, East Melbourne VIC 3002, Australia",
    time: "10AM-4PM",
    phone: 61396589658,
    website: "https://whatson.melbourne.vic.gov.au/things-to-do/cooks-cottage",
    brief:
      "Yorkshire cottage home to James Cook's family, shipped from England & rebuilt in a city park.",
    tag: "scenic point",
    lat: -37.81450513,
    long: 144.9794583,
    lineA: "",
    lineB: "",
    lineC: 5,
  },
  {
    name: "400 Gradi",
    address: "99 Lygon St, Brunswick East VIC 3057, Australia",
    time: "12-11PM",
    phone: 61393802320,
    website: "http://www.400gradi.com.au/",
    brief: "the Best Pizzeria in Oceania",
    tag: "dinner",
    lat: -37.77597865,
    long: 144.9708303,
    lineA: "",
    lineB: "",
    lineC: 6,
  },
  {
    name: "Calton Wine Room",
    address: "172-174 Faraday St, Carlton VIC 3053, Australia",
    time: "12-11PM",
    phone: 61393472626,
    website: "http://thecarltonwineroom.com.au/",
    brief:
      "Inventive tasting menus and a thoughtful wine list, at a chic restaurant in a 19th-century building.",
    tag: "dinner",
    lat: -37.79861549,
    long: 144.9686135,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Leonardo Pizza Palace",
    address: "29 Grattan St, Carlton VIC 3053, Australia",
    time: "12-11PM",
    phone: 61392420666,
    website: "http://www.leonardospizzapalace.com.au/",
    brief:
      "When stepping into?Leonardo's Pizza Palace, you'll immediately be transported to the world of the Sopranos and 70s Italian-American pizzerias.",
    tag: "dinner",
    lat: -37.80106283,
    long: 144.9686326,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Capitano",
    address: "421 Rathdowne St, Carlton VIC 3053, Australia",
    time: "5:30-11PM",
    phone: 61391348555,
    website: "http://www.capitano.com.au/",
    brief:
      "Pizza, pasta & other Italian favourites are served in this relaxed eatery that has a bar.",
    tag: "dinner",
    lat: -37.79649967,
    long: 144.9704329,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "DOC Espresso",
    address: "326 Lygon St, Carlton VIC 3053, Australia",
    time: "7AM-10PM",
    phone: 61393478482,
    website: "http://www.docgroup.net/",
    brief:
      "Artisan pizza and pasta dishes served in a popular Italian espresso bar and cafe with outside seats.",
    tag: "dinner",
    lat: -37.79929921,
    long: 144.9673701,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Hopscotch Melbourne",
    address: "Ground Floor, 4 Riverside Quay, Southbank VIC 3006, Australia",
    time: "12-12PM",
    phone: 61398100099,
    website: "https://hopscotchmelbourne.com.au/?utm_source=GMB",
    brief:
      "Buzzing riverside brewpub offering creative bar fare, burgers & a nitro ice-cream bar.",
    tag: "dinner",
    lat: -37.82072684,
    long: 144.9634493,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "BearBrass",
    address: "GR3A/3 Southgate Ave, Southbank VIC 3006, Australia",
    time: "11AM-11PM",
    phone: 61396823799,
    website: "https://bearbrass.com.au/",
    brief:
      "Fun, arty setting with city views and outdoor tables, for hearty breakfasts, tapas and pizza.",
    tag: "dinner",
    lat: -37.8201838,
    long: 144.9658607,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Cervo",
    address:
      "Crown Riverwalk, Crown Melbourne, 28/8 Whiteman Street, Southbank VIC 3006, Australia",
    time: "11:30AM-10PM",
    phone: 61396861488,
    website:
      "https://www.crownmelbourne.com.au/restaurants/casual/cervo?utm_source=google&utm_medium=organic&utm_content=cervo&utm_campaign=gmb",
    brief:
      "Upbeat Italian restaurant serving classic dishes in a cosy riverside space with bistro-style seats.",
    tag: "dinner",
    lat: -37.82309162,
    long: 144.9578338,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Ludlow Bar",
    address: "6 Riverside Quay, Southbank VIC 3006, Australia",
    time: "12-11PM",
    phone: 61396991676,
    website: "http://www.ludlowbar.com.au/",
    brief:
      "Rustic-chic pub and grill serving southern European-style food and featuring live DJs on weekends.",
    tag: "dinner",
    lat: -37.8206663,
    long: 144.9637848,
    lineA: "",
    lineB: "",
    lineC: "",
  },
  {
    name: "Eureka 89 Dining",
    address:
      "Level 89, Eureka Tower, 7 Riverside Quay, Southbank VIC 3006, Australia",
    time: "5:30-9PM",
    phone: 61396938889,
    website: "http://www.eureka89.com.au/",
    brief:
      "Seasonal tasting menus & a robust wine list offered in a sleek venue featuring bay & city views.",
    tag: "dinner",
    lat: -37.82124348,
    long: 144.9644603,
    lineA: "",
    lineB: 7,
    lineC: "",
  },
  {
    name: "Waterfront Southgate",
    address:
      "Southgate Precinct, 20/3 Southgate Ave, Southbank VIC 3006, Australia",
    time: "12-3:30PM, 6-9PM",
    phone: 61396869766,
    website: "http://waterfrontsouthgate.com.au/",
    brief:
      "Sashimi, seafood platters and grilled meat served in a modern dining room with booth seats.",
    tag: "dinner",
    lat: -37.82022519,
    long: 144.9656533,
    lineA: "",
    lineB: "",
    lineC: "",
  },
];
